version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_SECRET_KEY=dev-secret
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=password123

